### ISSUE TITLE
Missing "Team" entry on landing navbar

### ISSUE THREAD

**Issue by feliciofilipe** [joinum/parzival#81]

**Comment by RuiL1904** [comment]
![image](https://user-images.githubusercontent.com/76881129/166494406-4d53b292-0cb7-4e3f-b6f5-ad1cfcbe53ec.png)
I would like to work on this one, but what do you mean with "Team" entry on landing _navbar_? I see it right there 🤔

**Comment by RuiL1904** [comment]
Closed by #87.
